/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeHomeRouteImport } from './routes/(home)/_home'
import { Route as homeHomeIndexRouteImport } from './routes/(home)/_home.index'
import { Route as homeHomeAboutRouteImport } from './routes/(home)/_home.about'

const homeHomeRoute = homeHomeRouteImport.update({
  id: '/(home)/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const homeHomeIndexRoute = homeHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeHomeRoute,
} as any)
const homeHomeAboutRoute = homeHomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => homeHomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof homeHomeAboutRoute
  '/': typeof homeHomeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof homeHomeAboutRoute
  '/': typeof homeHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/_home': typeof homeHomeRouteWithChildren
  '/(home)/_home/about': typeof homeHomeAboutRoute
  '/(home)/_home/': typeof homeHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/'
  id: '__root__' | '/(home)/_home' | '/(home)/_home/about' | '/(home)/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeHomeRoute: typeof homeHomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/_home': {
      id: '/(home)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof homeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/_home/': {
      id: '/(home)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeIndexRouteImport
      parentRoute: typeof homeHomeRoute
    }
    '/(home)/_home/about': {
      id: '/(home)/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeHomeAboutRouteImport
      parentRoute: typeof homeHomeRoute
    }
  }
}

interface homeHomeRouteChildren {
  homeHomeAboutRoute: typeof homeHomeAboutRoute
  homeHomeIndexRoute: typeof homeHomeIndexRoute
}

const homeHomeRouteChildren: homeHomeRouteChildren = {
  homeHomeAboutRoute: homeHomeAboutRoute,
  homeHomeIndexRoute: homeHomeIndexRoute,
}

const homeHomeRouteWithChildren = homeHomeRoute._addFileChildren(
  homeHomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  homeHomeRoute: homeHomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
